#!/usr/bin/env bash

VERSION=$(egrep -o "version='([0-9.])+" setup.py | cut -c 10-)
PREFIX=dist/*-$VERSION
echo Version: $VERSION
python setup.py bdist_wheel
python setup.py sdist
twine upload $PREFIX.* $PREFIX-*
